import { ExternalLink } from '../components/ExternalLink';

interface Work {
   title: string;
   company: {
      name: string;
      link: string;
   };
   tags: string[];
   active: boolean;
   entries: [string, React.ReactNode][];
}

export const WORKS: Work[] = [
   {
      title: 'Full-Stack Developer',
      company: {
         name: 'Galadrim',
         link: 'https://galadrim.fr/',
      },
      tags: ['2020 -> Now', 'Galadrim', 'France'],
      active: true,
      entries: [
         [
            'Description',
            <>
               {`▹ Writing modern, performant, maintainable code for multiple client and platforms (web & mobile)`}
               <br />
               {`▹ Work with a variety of different languages, tools, frameworks, and content management systems`}
               <br />
               {`▹ Communicate with multi-disciplinary teams of engineers and clients on a daily basis`}
               <br />
               {`▹ Mentoring newcomers and writing technical articles`}
            </>,
         ],
         [
            'Technologies',
            '▹ Typescript ▹ React.js ▹ React Native ▹ Next.js ▹ NestJS ▹ MobX ▹ Redux ▹ AWS ▹ GCP ▹ OVH ▹ TailwindCSS ▹ Material-UI ▹ Prisma ▹ TypeORM ▹ MySQL ▹ PostgreSQL ▹ GraphQL ▹ Relay ▹ GitLab CI/CD ▹ GitHub Actions',
         ],
         ['Methodologies', '▹ Agile ▹ Test-Driven Development'],
      ],
   },
   {
      title: 'Innovation Finance Consultant',
      company: {
         name: 'III Financements',
         link: 'http://www.iii-financements.com/',
      },
      tags: ['2019 -> Now', 'III Financements', 'France'],
      active: true,
      entries: [
         [
            'Description',
            '▹ Writing technical documents for start-ups and SMEs in the context of fundraising applications to Bpifrance',
         ],
         ['Technologies', '▹ Microsoft Word ▹ Microsoft Excel ▹ Microsoft PowerPoint'],
      ],
   },
   {
      title: 'Software Engineer Intern',
      company: {
         name: 'Viveris',
         link: 'https://www.viveris.fr/',
      },
      tags: ['March 2019 -> September 2019', 'Viveris', 'France'],
      active: false,
      entries: [
         [
            'Description',
            <>
               {`▹ Worked with a R&D team of five researchers as a software engineer to improve `}
               <ExternalLink label="OpenSAND homepage" href="http://opensand.org/content/home.php">
                  OpenSAND
               </ExternalLink>
               {`, a 10+ years old software promoted by the `}
               <ExternalLink label="CNES homepage" href="https://cnes.fr/en">
                  CNES
               </ExternalLink>
               {` (french space center) and emulating satellite communication systems`}
               <br />
               {`▹ Architected an efficient and generic configuration library using C++ to define metamodels and datamodels that can be dynamically loaded and saved to files`}
               <br />
               {`▹ Developed a generic web HMI, automatically generated by parsing a metamodel and allowing to generate a datamodel to be live-loaded by OpenSAND ; Python3 bindings have been used to communicate between C++ and React.JS`}
               <br />
               {`▹ Designed a modern topology HMI allowing OpenSAND entities management, metamodels and datamodels management`}
            </>,
         ],
         [
            'Technologies',
            '▹ Software architecture ▹ Typescript ▹ React.JS ▹ Python ▹ C++ ▹ Catch2 ▹ Boost ▹ CMake ▹ DevOps',
         ],
      ],
   },
];
